### ISSUE TITLE
When returning from Guide Live Channels don't work anymore

### ISSUE THREAD

**Issue by acuntex** [Fleker/CumulusTV#132]
When I'm in the guide to see the program channel list and i go o a channel, it's not working any more and I have to restart the tv.

```
W/TunableTvView( 3796): [Main] onVideoUnavailable(inputId=com.felkertech.n.cumulustv/.CumulusTvService, reason=3
D/Utils   ( 3796): packageName is com.felkertech.n.cumulustv
W/TvActivity( 3796): [Main] onVideoUnavailable(inputId=com.felkertech.n.cumulustv/.CumulusTvService reason = 3) current time = 1467560019245
D/Utils   ( 3796): packageName is com.felkertech.n.cumulustv
W/MessageQueue( 5126):  at com.felkertech.n.cumulustv.CumulusTvService.onTune(CumulusTvService.java:212)
W/MessageQueue( 5126):  at com.felkertech.n.cumulustv.livechannels.CumulusSessions$TuningTask$1.handleMessage(CumulusSessions.java:123)
D/cumulus:TvInputPlayer( 5126): Prep HLS
W/TunableTvView( 3796): [Main] onVideoUnavailable(inputId=com.felkertech.n.cumulustv/.CumulusTvService, reason=3
D/Utils   ( 3796): packageName is com.felkertech.n.cumulustv
W/TvActivity( 3796): [Main] onVideoUnavailable(inputId=com.felkertech.n.cumulustv/.CumulusTvService reason = 3) current time = 1467560019311
D/Utils   ( 3796): packageName is com.felkertech.n.cumulustv
W/TunableTvView( 3796): [Main] onVideoAvailable(inputId=com.felkertech.n.cumulustv/.CumulusTvService
D/TvActivity( 3796): [Main] onVideoAvailable(inputId=com.felkertech.n.cumulustv/.CumulusTvService) current time = 1467560019338
D/Utils   ( 3796): packageName is com.felkertech.n.cumulustv
D/CurrentState( 3796): setMainInputInfo : com.felkertech.n.cumulustv/.CumulusTvService|6179:null
```

**Comment by Fleker** [comment]
Are you using a Sony TV?

**Comment by Fleker** [comment]
Unfortunately this is currently a known issue. You should be able to fix by going to a channel not from CumulusTV and return.

**Comment by Fleker** [comment]
This should be fixed soon.

**Comment by Fleker** [comment]
Fixed by using the TIF Companion Lib
