### ISSUE TITLE
Index out-of-bounds exception in CardPresenter

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#170]
Crash report:
 
   Fatal Exception: java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
       at java.util.ArrayList.get(ArrayList.java:411)
       at java.util.Collections$UnmodifiableList.get(Collections.java:1295)
       at com.felkertech.n.tv.presenters.CardPresenter$1$1.run(CardPresenter.java:103)
       at android.os.Handler.handleCallback(Handler.java:751)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:154)
       at android.app.ActivityThread.main(ActivityThread.java:6077)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by Fleker** [comment]
Happens when there are no swatches available.
