### ISSUE TITLE
Mobile sync sometimes creates issues as it doesn't have TV Database

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#232]
Seems to be an issue on some devices that omit `android.media.tv` content resolver. Seems like I have to make sure that this code only will run on TVs (or devices with this content resolver).

    Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:325)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
    Caused by java.lang.IllegalArgumentException: Unknown URL content://android.media.tv/channel
       at android.content.ContentResolver.insert(ContentResolver.java:1275)
       at com.google.android.media.tv.companionlibrary.utils.TvContractUtils.updateChannels(TvContractUtils.java:126)
       at com.google.android.media.tv.companionlibrary.EpgSyncJobService$EpgSyncTask.doInBackground(EpgSyncJobService.java:382)
       at com.google.android.media.tv.companionlibrary.EpgSyncJobService$EpgSyncTask.doInBackground(EpgSyncJobService.java:359)
       at android.os.AsyncTask$2.call(AsyncTask.java:305)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by Fleker** [comment]
Should be fixed in next update by hiding EPG syncing on non-TV devices
