### ISSUE TITLE
[M3u Parser] Handle cases when channel number is undefined

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#248]
Getting this crash

    01-31 02:00:20.837 5217-5605/com.felkertech.n.cumulustv D/M3uParser: #EXTINF:0 tvg-id="" tvg-name="YourTV UK" tvg-logo="" group-title="Rapid" parent-code=""
    01-31 02:00:20.837 5217-5605/com.felkertech.n.cumulustv D/M3uParser: tvg-id="" tvg-name="YourTV UK" tvg-logo="" group-title="Rapid" parent-code=""
    01-31 02:00:20.837 5217-5605/com.felkertech.n.cumulustv D/M3uParser: tvg-name="YourTV UK" tvg-logo="" group-title="Rapid" parent-code=""
    01-31 02:00:20.837 5217-5605/com.felkertech.n.cumulustv D/M3uParser: tvg-logo="" group-title="Rapid" parent-code=""
    01-31 02:00:20.837 5217-5605/com.felkertech.n.cumulustv D/M3uParser: group-title="Rapid" parent-code=""
    01-31 02:00:20.837 5217-5605/com.felkertech.n.cumulustv D/M3uParser: parent-code=""
    01-31 02:00:20.840 5217-5605/com.felkertech.n.cumulustv D/M3uParser: Done parsing
                                                                     
                                                                     --------- beginning of crash
    01-31 02:00:20.841 5217-5605/com.felkertech.n.cumulustv E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                          Process: com.felkertech.n.cumulustv, PID: 5217
                                                                          java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                              at android.os.AsyncTask$3.done(AsyncTask.java:318)
                                                                              at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                              at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:761)
                                                                           Caused by: java.lang.IllegalArgumentException: Number must be defined.
                                                                              at com.felkertech.cumulustv.plugins.CumulusChannel$Builder.build(CumulusChannel.java:248)
                                                                              at com.felkertech.cumulustv.model.JsonChannel$Builder.build(JsonChannel.java:176)
                                                                              at com.felkertech.cumulustv.fileio.M3uParser$M3uTvChannel.toJsonChannel(M3uParser.java:211)
                                                                              at com.felkertech.cumulustv.fileio.M3uParser$M3uTvChannel.toString(M3uParser.java:216)
                                                                              at com.felkertech.cumulustv.fileio.M3uParser$TvListing.toString(M3uParser.java:172)
                                                                              at com.felkertech.cumulustv.fileio.M3uParser.parse(M3uParser.java:140)
                                                                              at com.felkertech.cumulustv.activities.FileIoTestActivity.parse(FileIoTestActivity.java:152)
                                                                              at com.felkertech.cumulustv.activities.FileIoTestActivity.access$100(FileIoTestActivity.java:38)
                                                                              at com.felkertech.cumulustv.activities.FileIoTestActivity$2$3.onFileLoaded(FileIoTestActivity.java:135)
                                                                              at com.felkertech.cumulustv.fileio.HttpFileParser$DownloadWebpageTask.doInBackground(HttpFileParser.java:34)
                                                                              at com.felkertech.cumulustv.fileio.HttpFileParser$DownloadWebpageTask.doInBackground(HttpFileParser.java:27)
                                                                              at android.os.AsyncTask$2.call(AsyncTask.java:304)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243) 
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133) 
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607) 
                                                                              at java.lang.Thread.run(Thread.java:761)

**Comment by Fleker** [comment]
This is because `tvg-id` is an empty string. It can be resolved by checking empty strings before putting in the value.
