### ISSUE TITLE
Sony Bravia running Android TV 6.0.1, constant crashes upon TV boot

### ISSUE THREAD

**Issue by nextux** [Fleker/CumulusTV#272]
Hi @Fleker 

My TV got updated from 5.1.1 to 6.0.1.  Upon load, it still uses Sony's own "Streaming Channels" app, however, the issue is that Cumulus TV keeps FC'ing upon the TV being booted up.

Reporting the issue is hard as it constantly comes up with the FC.

I managed to get two reports through around 5 mins ago.

Unsure what is causing it to crash though. I even "Factory Data Reset" my TV in hope that would fix it, but to no avail.

**Comment by Fleker** [comment]
Thanks for the report.

Here's a likely stacktrace:

     java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set java.util.HashMap.keySet()' on a null object reference
	at com.felkertech.cumulustv.tv.CumulusTvTifService$RichTvInputSessionImpl.onTune(CumulusTvTifService.java:316)
	at android.media.tv.TvInputService$Session.onTune(TvInputService.java:787)
	at android.media.tv.TvInputService$Session.tune(TvInputService.java:1134)
	at android.media.tv.ITvInputSessionWrapper.executeMessage(ITvInputSessionWrapper.java:126)
	at com.android.internal.os.HandlerCaller$MyHandler.handleMessage(HandlerCaller.java:37)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.app.ActivityThread.main(ActivityThread.java:5417)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by nextux** [comment]
It seemed to be crashing randomly upon loading the "Streaming Channels" app normally, but more prevalent if upon boot the TV tried tuning into Streaming Channels immediately.

**Comment by nextux** [comment]
Could https://github.com/Fleker/CumulusTV/issues/254 be connected with the same bug?

**Comment by Fleker** [comment]
I'm sure they are related. It's due to some channels' metadata taking
longer to load and process. I currently don't cache it.

**Comment by nextux** [comment]
1.7.9 seems to fix this issue.  Not crashing anymore.
