### ISSUE TITLE
Crash Report [1.3.0, MainActivity:588]

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#42]
java.lang.ClassCastException: java.util.ArrayList cannot be cast to com.felkertech.n.cumulustv.xmltv.Program
       at com.felkertech.n.cumulustv.MainActivity$12$4.run(MainActivity.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by Fleker** [comment]
This is based around the `XMLTVParser`. I don't know why this broke, but it's not going to matter as it's an experimental feature.
