### ISSUE TITLE
Recognize invalid logos

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#47]
From this crash

    java.lang.IllegalStateException: Unrecognized type of request: Request{aljazeera.jpg}
       at com.squareup.picasso.BitmapHunter$2.load(BitmapHunter.java:66)
       at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
       at com.squareup.picasso.RequestCreator.get(RequestCreator.java:396)
       at com.felkertech.n.cumulustv.SampleTvInput$SimpleSessionImpl$1.run(SampleTvInput.java:211)
       at java.lang.Thread.run(Thread.java:818)

**Comment by Fleker** [comment]
This will be fixed in 1.3.6
