### ISSUE TITLE
Support Marshmallow

### ISSUE THREAD

**Issue by Fleker** [Fleker/CumulusTV#48]
Got this error. Seems to be on lollipop though so I don't really know why it's wigging out:

    java.lang.SecurityException: Permission Denial: writing com.android.providers.tv.TvProvider uri content://android.media.tv/program/371183 from pid=6356, uid=10077 requires com.android.providers.tv.permission.WRITE_EPG_DATA, or grantUriPermission()
       at android.os.Parcel.readException(Parcel.java:1546)
       at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:185)
       at android.database.DatabaseUtils.readExceptionWithOperationApplicationExceptionFromParcel(DatabaseUtils.java:160)
       at android.content.ContentProviderProxy.applyBatch(ContentProviderNative.java:520)
       at android.content.ContentProviderClient.applyBatch(ContentProviderClient.java:377)
       at android.content.ContentResolver.applyBatch(ContentResolver.java:1244)
       at com.example.android.sampletvinput.syncadapter.SyncAdapter$1.run(SyncAdapter.java:497)
       at java.lang.Thread.run(Thread.java:818)

**Comment by Fleker** [comment]
Another thing, this time from a Marshmallow device. We need to add support

    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.felkertech.n.cumulustv/com.felkertech.n.cumulustv.SampleSetup}: java.lang.SecurityException: no permission to write the sync settings: Neither user 10085 nor current process has android.permission.WRITE_SYNC_SETTINGS.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
Caused by: java.lang.SecurityException: no permission to write the sync settings: Neither user 10085 nor current process has android.permission.WRITE_SYNC_SETTINGS.
       at android.os.Parcel.readException(Parcel.java:1599)
       at android.os.Parcel.readException(Parcel.java:1552)
       at android.content.IContentService$Stub$Proxy.setIsSyncable(IContentService.java:1204)
       at android.content.ContentResolver.setIsSyncable(ContentResolver.java:2184)
       at com.example.android.sampletvinput.syncadapter.SyncUtils.setUpPeriodicSync(SyncUtils.java:42)
       at com.felkertech.n.cumulustv.SampleSetup.onCreate(SampleSetup.java:63)
       at android.app.Activity.performCreate(Activity.java:6237)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
       at android.app.ActivityThread.-wrap11(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5417)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
