### ISSUE TITLE
Latest update crashes upon open

### ISSUE THREAD

**Issue by alanmcramer** [Fleker/CumulusTV#77]
Unable to use the app as it crashes upon open.  I have tried setting manual permission for storage.  I have cleared the data.

Just get "Unfortunately, Cumulus TV has stopped."

Running Android 6.0 on Asus Nexus Player.  Build MRA58N.

**Comment by BradleyRL** [comment]
same on my ADT-1

**Comment by Fleker** [comment]
That's pretty odd, but I'll look at it this weekend.

**Comment by Fleker** [comment]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.felkertech.n.cumulustv/com.felkertech.n.tv.LeanbackActivity}: java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
Caused by java.lang.IllegalStateException: You need to use a Theme.AppCompat theme (or descendant) with this activity.
       at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:311)
       at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:280)
       at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:254)
       at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:109)
       at com.felkertech.n.tv.LeanbackActivity.onCreate(LeanbackActivity.java:48)
       at android.app.Activity.performCreate(Activity.java:5933)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
       at android.app.ActivityThread.access$800(ActivityThread.java:144)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:135)
       at android.app.ActivityThread.main(ActivityThread.java:5221)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)

**Comment by alanmcramer** [comment]
So is this something google has changed or something introduced in the latest app update?

**Comment by alanmcramer** [comment]
Using HAL (Handheld App Launcher) and selecting "Cumulus TV (Handheld)" allowed me to open the app (in the mobile interface) and prevent unhappy wife.

**Comment by Fleker** [comment]
Yeah it looks like a problem in the Leanback library.

**Comment by Fleker** [comment]
Fixed

**Comment by jmriquin** [comment]
Unfortunately the same problem remains on freebox 4k

**Comment by Fleker** [comment]
I'll be looking at the crash logs
